image: node:10.5.0

stages:
    - build
    - test
    - deploy

before_script:
    - npm install

build-code:
    stage: build
    script:
        - npm install
        - npm run build
        
deploy-staging:
    stage: deploy
    script:
        - npm start
    only:
        - develop
        
deploy-production:
    stage: deploy
    script:
        - npm run prod
    only:
        - release