version: '3.9'

services: 
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
        MYSQL_ROOT_PASSWORD: root2022
        MYSQL_DATABASE: my_crm_db
        MYSQL_USER: mateocorp
        MYSQL_PASSWORD: mateocorp2022
    ports:
      - 3306:3306

    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  adminer:
    image: adminer
    restart: always
    ports: 
        - 8080:8080

volumes: 
  db-config:
  db-data: